---
title: "Weather forecasts"
output: html_notebook
---
```{r}
saveRDS(analysed_data, file = "analysed_data.rds")
```



Set Working Directory, Load Config and Source Files
```{r}

    #setwd("~/r_project/Client")
    setwd("C:/Users/Karolina/Desktop/semestr VII/Programowanie w R/Projekt/r_project/Client/Rprojekt")
    source(file = "config.R")
    source(file = "arrangement.R")
    source(file = "geolocation.R")
    source(file = "forecasting.R")
    source(file = "preparations.R")
    source(file = "plots.R")
    source(file = "map.R")

    config <- load_config()
```

Try to load data from file, if not available, download and prepare data
```{r}
    if (file.exists("analysed_data.rds")) {
        analysed_data <- readRDS("analysed_data.rds")
    } else {
        preselected_data    <- preselect_data();
        prepared_data       <- download_and_prepare_data(preselected_data)
        best_forecast_model <- estimate_best_forecast_model(prepared_data)
        analysed_data       <- forecast_data(prepared_data, best_forecast_model)
        saveRDS(analysed_data, file = "analysed_data.rds")
    }
```

Try to load plots from file, if not available, create plots
```{r}
    if (file.exists("plots.rds")) {
        plots <- readRDS("plots.rds")
    } else {
        plots <- create_plots(analysed_data)
        saveRDS(plots, file = "plots.rds")
    }
```

Print Yearly Plots
```{r}
    print(plots$Historical$Yearly$TMAX)
    print(plots$Historical$Yearly$TMIN)
```

Print Monthly Plots
```{r}
    for (month in seq(1, length(plots$Forecasted$Monthly))) {
        print(plots$Forecasted$Monthly[[month]]$TMAX)
        print(plots$Forecasted$Monthly[[month]]$TMIN)
    }
```



World map
```{r}
# Wybrany miesiąc i rok
selected_month <-4
selected_year <- 2020
# Przetwarzanie danych na listy
lon <- lapply(analysed_data, function(x) x$Informations$Lon)
lat <- lapply(analysed_data, function(x) x$Informations$Lat)
station_ID <- lapply(analysed_data, function(x) x$Informations$Station_ID)
temperature <- lapply(analysed_data, function(x) x$Measurements$MeasurementValue)

# Rysowanie mapy
world_map <- createWorldMap(lat, lon, station_ID, temperature)
world_map
```
